name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # 2 jeer maalintii
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: caaqilyare
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif

      - name: Push snake files
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update snake animation"
          add: "dist/*"
